CREATE TABLE "amostras" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "amostras_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"texto_extraido" text,
	"avaliador_id" integer NOT NULL,
	"proponente" text,
	"cpf" varchar(14),
	"cnpj" varchar(18),
	"ddd" varchar(3),
	"telefone" varchar(20),
	"endereco_literal" text,
	"coordenada_s" text,
	"coordenada_w" text,
	"complemento" text,
	"bairro" text,
	"cep" varchar(15),
	"municipio" text,
	"uf" char(2),
	"empresa_responsavel" text,
	"valor_terreno" real,
	"matricula" text,
	"oficio" text,
	"comarca" text,
	"uf_matricula" char(2),
	"valor_imovel" real,
	"incidencias" real[],
	"numero_etapas" integer,
	"acumulado_proposto" real[],
	"valor_unitario" real,
	"testada" real,
	"idade_estimada" text,
	"area_terreno" real,
	"area_construida" real,
	"quartos" integer,
	"banheiros" integer,
	"suites" integer,
	"vagas" integer,
	"padrao_acabamento" text,
	"estado_conservacao" text,
	"infraestrutura" text,
	"servicos_publicos" text,
	"usos_predominantes" text,
	"via_acesso" text,
	"regiao_contexto" text,
	"data_referencia" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "avaliadores" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "avaliadores_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" text NOT NULL,
	"nome_fantasia" text NOT NULL,
	"cpf" varchar(14) NOT NULL,
	"cnpj" varchar(18) NOT NULL,
	"registro_crea" varchar(25) NOT NULL,
	CONSTRAINT "avaliadores_cpf_unique" UNIQUE("cpf"),
	CONSTRAINT "avaliadores_cnpj_unique" UNIQUE("cnpj")
);
--> statement-breakpoint
ALTER TABLE "amostras" ADD CONSTRAINT "amostras_avaliador_id_avaliadores_id_fk" FOREIGN KEY ("avaliador_id") REFERENCES "public"."avaliadores"("id") ON DELETE no action ON UPDATE no action;